# Generated by Django 5.1 on 2024-08-11 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spotify_history', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listen_history',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_history.album'),
        ),
        migrations.AddField(
            model_name='listen_history',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_history.song'),
        ),
        migrations.AddField(
            model_name='artist_song',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_history.song'),
        ),
        migrations.AlterUniqueTogether(
            name='artist_album',
            unique_together={('artist', 'album')},
        ),
        migrations.AlterUniqueTogether(
            name='listen_history',
            unique_together={('account', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='artist_song',
            unique_together={('artist', 'song')},
        ),
    ]
