# Use the official PostgreSQL image from the Docker Hub
FROM postgres:16

# Copy any custom configuration files (optional)
# COPY custom.conf /etc/postgresql/conf.d/

# Use a volume for persistent data storage (optional)
VOLUME ["/var/lib/postgresql/data"]

# Start PostgreSQL
CMD ["postgres"]
