# redis/Dockerfile

FROM redis:7-alpine

# # Copy SSL certificates into the container
# COPY ./ssl/shared.crt /etc/ssl/shared.crt
# COPY ./ssl/shared.key /etc/ssl/shared.key

# COPY start.sh /start.sh

# # Set the Redis command with SSL configuration
# CMD ["/start.sh"]